name: Create release
on:
  push:
    branches:
      - master
  pull_request:
    types: [openend, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit, composer
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: carlosabcs/lumen-phpunit-action@master
      - name: Upload tests results
        uses: actions/upload-artifact@v4
        with:
          name: phpunit
          path: |
            coverage.xml
            junit.xml
  update_release_draft:
    needs: build
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-master.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}